/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        final String greeting = "Hello World";
        return greeting;
    }

    public static void main(final String[] args) {
        System.out.println(new App().getGreeting());
    }
}
